package com.volunteer.platform.service;

import com.volunteer.platform.model.*;
import com.volunteer.platform.repository.HourLogRepository;
import com.volunteer.platform.repository.RegistrationRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * =====================================================================
 * HourLogService (Business Logic Layer)
 * ---------------------------------------------------------------------
 * Handles volunteer service hour submissions.
 * Hours are counted immediately when submitted — no approval step.
 * - Only permits hour submissions for registrations marked ATTENDED
 * - Enforces the "max_hours_per_log" system setting constraint
 * - Aggregates total hours for platform, organization, and volunteer stats
 * =====================================================================
 */
@SuppressWarnings("null")
@Service
public class HourLogService {

    private final HourLogRepository hourLogRepository;
    private final RegistrationRepository registrationRepository;
    private final SettingService settingService;
    private final ActivityLogService activityLogService;

    /**
     * Constructor injecting repositories, setting service, and audit service.
     */
    public HourLogService(HourLogRepository hourLogRepository,
                          RegistrationRepository registrationRepository,
                          SettingService settingService,
                          ActivityLogService activityLogService) {
        this.hourLogRepository = hourLogRepository;
        this.registrationRepository = registrationRepository;
        this.settingService = settingService;
        this.activityLogService = activityLogService;
    }

    /**
     * Submits or updates service hours logged by a volunteer who attended an event.
     * Hours are recorded immediately — no organization approval required.
     */
    @Transactional
    public HourLog logHours(Long registrationId, double hours, String workDescription, User volunteer) {
        Registration registration = registrationRepository.findById(registrationId)
                .orElseThrow(() -> new IllegalArgumentException("Registration not found with id: " + registrationId));

        if (!registration.getVolunteer().getId().equals(volunteer.getId())) {
            throw new IllegalArgumentException("You are not authorized to log hours for this registration.");
        }

        if (registration.getStatus() != RegistrationStatus.ATTENDED) {
            throw new IllegalStateException("Hours can only be logged for events where your attendance was marked ATTENDED.");
        }

        if (hours <= 0) {
            throw new IllegalArgumentException("Logged hours must be greater than 0.");
        }

        int maxHours = settingService.getInt("max_hours_per_log", 12);
        if (hours > maxHours) {
            throw new IllegalArgumentException("Logged hours cannot exceed the system limit of " + maxHours + " hours per entry.");
        }

        Optional<HourLog> existingOpt = hourLogRepository.findFirstByRegistrationOrderByLoggedAtDesc(registration);
        HourLog logEntry;
        if (existingOpt.isPresent()) {
            logEntry = existingOpt.get();
            logEntry.setHours(hours);
            logEntry.setWorkDescription(workDescription != null ? workDescription.trim() : null);
            logEntry.setLoggedAt(LocalDateTime.now());
        } else {
            logEntry = new HourLog(registration, hours, workDescription != null ? workDescription.trim() : null);
        }

        HourLog saved = hourLogRepository.save(logEntry);
        activityLogService.log(volunteer, "Volunteer logged " + hours + " hours for: " +
                registration.getOpportunity().getTitle());
        return saved;
    }

    /**
     * Finds the existing hour log for a registration if one has been submitted.
     */
    public Optional<HourLog> getHourLogForRegistration(Registration registration) {
        return hourLogRepository.findFirstByRegistrationOrderByLoggedAtDesc(registration);
    }

    /**
     * Retrieves all hour logs submitted by a volunteer.
     */
    public List<HourLog> getHoursByVolunteer(User volunteer) {
        return hourLogRepository.findByRegistrationVolunteerOrderByLoggedAtDesc(volunteer);
    }

    /**
     * Calculates total volunteer service hours across the entire platform.
     */
    public double getTotalHoursPlatform() {
        return hourLogRepository.sumAllHours();
    }

    /**
     * Calculates total service hours logged by a specific volunteer.
     */
    public double getTotalHoursForVolunteer(User volunteer) {
        return hourLogRepository.sumHoursByVolunteer(volunteer);
    }

    /**
     * Calculates total service hours generated by an organization's events.
     */
    public double getTotalHoursForOrganization(User organization) {
        return hourLogRepository.sumHoursByOrganization(organization);
    }

    /**
     * Calculates total service hours logged for a single opportunity event.
     */
    public double getTotalHoursForOpportunity(Opportunity opportunity) {
        return hourLogRepository.sumHoursByOpportunity(opportunity);
    }
}
