package com.volunteer.platform.repository;

import com.volunteer.platform.model.*;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * =====================================================================
 * HourLogRepository (Data Access Layer)
 * ---------------------------------------------------------------------
 * Handles database operations for volunteer service hours.
 * Hours count immediately — no status/approval needed.
 * =====================================================================
 */
@Repository
public interface HourLogRepository extends JpaRepository<HourLog, Long> {

    /**
     * Finds the most recent hour log for a specific registration (if submitted).
     */
    Optional<HourLog> findFirstByRegistrationOrderByLoggedAtDesc(Registration registration);

    /**
     * Retrieves all hour logs submitted by a volunteer.
     */
    List<HourLog> findByRegistrationVolunteerOrderByLoggedAtDesc(User volunteer);

    /**
     * Calculates the total sum of all hours logged by a specific volunteer.
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h WHERE h.registration.volunteer = :volunteer")
    double sumHoursByVolunteer(@Param("volunteer") User volunteer);

    /**
     * Calculates the total sum of hours logged across the entire platform.
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h")
    double sumAllHours();

    /**
     * Calculates the total sum of hours generated by an organization's events.
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h WHERE h.registration.opportunity.organization = :org")
    double sumHoursByOrganization(@Param("org") User org);

    /**
     * Calculates the total sum of hours logged for a single opportunity event.
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h WHERE h.registration.opportunity = :opportunity")
    double sumHoursByOpportunity(@Param("opportunity") Opportunity opportunity);
}
