package com.volunteer.platform.repository;

import com.volunteer.platform.model.*;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * =====================================================================
 * HourLogRepository (Data Access Layer)
 * ---------------------------------------------------------------------
 * Handles database operations for volunteer service hours.
 * Includes methods for hour submissions, approvals, and aggregation
 * queries (SUM of approved hours for platform, org, and volunteer).
 * =====================================================================
 */
@Repository
public interface HourLogRepository extends JpaRepository<HourLog, Long> {

    /**
     * Retrieves all hour logs tied to a specific registration.
     */
    List<HourLog> findByRegistration(Registration registration);

    /**
     * Finds the hour log for a specific registration (if already submitted).
     */
    Optional<HourLog> findFirstByRegistrationOrderByLoggedAtDesc(Registration registration);

    /**
     * Retrieves all hour logs across the platform matching a review status.
     */
    List<HourLog> findByStatus(HourLogStatus status);

    /**
     * Retrieves all hour logs submitted by a volunteer.
     */
    List<HourLog> findByRegistrationVolunteerOrderByLoggedAtDesc(User volunteer);

    /**
     * Retrieves hour logs for an organization's events filtered by approval status.
     */
    @Query("SELECT h FROM HourLog h WHERE h.registration.opportunity.organization = :org AND h.status = :status ORDER BY h.loggedAt DESC")
    List<HourLog> findByOrganizationAndStatus(@Param("org") User org, @Param("status") HourLogStatus status);

    /**
     * Counts pending hour submissions awaiting an organization's review.
     */
    @Query("SELECT COUNT(h) FROM HourLog h WHERE h.registration.opportunity.organization = :org AND h.status = :status")
    long countByOrganizationAndStatus(@Param("org") User org, @Param("status") HourLogStatus status);

    /**
     * Calculates the total sum of hours across the entire platform matching a given status (e.g., APPROVED).
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h WHERE h.status = :status")
    double sumHoursByStatus(@Param("status") HourLogStatus status);

    /**
     * Calculates the total sum of approved hours earned by a specific volunteer.
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h WHERE h.registration.volunteer = :volunteer AND h.status = :status")
    double sumHoursByVolunteerAndStatus(@Param("volunteer") User volunteer, @Param("status") HourLogStatus status);

    /**
     * Calculates the total sum of approved hours generated by an organization's events.
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h WHERE h.registration.opportunity.organization = :org AND h.status = :status")
    double sumHoursByOrganizationAndStatus(@Param("org") User org, @Param("status") HourLogStatus status);

    /**
     * Calculates the total sum of approved hours generated by a single opportunity event.
     */
    @Query("SELECT COALESCE(SUM(h.hours), 0.0) FROM HourLog h WHERE h.registration.opportunity = :opportunity AND h.status = :status")
    double sumHoursByOpportunityAndStatus(@Param("opportunity") Opportunity opportunity, @Param("status") HourLogStatus status);
}
